enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
